# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Karen Hinh
tagline:          'Mechanical Engineer'
description:      'A student at Olin College.'
url:              https://www.linkedin.com/in/karen-hinh/
baseurl:          https://karneh.github.io/

author:
  name:           'Karen Hinh'
  url:            https://www.linkedin.com/in/karen-hinh/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/karneh/hyde
