# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tabitha Davison
tagline:          'Mechanical Engineer'
description:      'A student at Olin College.'
url:              https://www.linkedin.com/in/tabithadavison 
baseurl:          https://tabitha-davison.github.io/

author:
  name:           'Tabitha Davison'
  url:            https://www.linkedin.com/in/tabithadavison 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://tabitha-davison.github.io/
